export const styles = {
  page: {
    fontFamily: "Inter, system-ui, sans-serif",
    background: "#F4F9FF", 
    minHeight: "100vh",
    padding: 20,
  },
  container: { maxWidth: 960, margin: "0 auto" },
  card: {
    background: "#FFFFFF",
    borderRadius: 16,
    padding: 18,
    boxShadow: "0 6px 16px rgba(0, 45, 90, 0.08)",
    marginBottom: 16,
  },
  input: {
    flex: 1,
    padding: "12px 14px",
    borderRadius: 12,
    border: "1px solid #D0E3FF",
    background: "#FFFFFF",
    fontSize: 16,
  },
  blueBtn: {
    background: "#4DA8FF",
    border: "none",
    padding: "12px 18px",
    borderRadius: 12,
    cursor: "pointer",
    fontWeight: 700,
    color: "#fff",
    boxShadow: "0 4px 12px rgba(0, 102, 204, 0.25)",
  },
  bottomNav: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    paddingBottom: 12,
    display: "flex",
    justifyContent: "center",
    pointerEvents: "none",
  },
  navBar: {
    width: 360,
    background: "#FFFFFF",
    borderRadius: 999,
    padding: 10,
    display: "flex",
    justifyContent: "space-around",
    boxShadow: "0 8px 24px rgba(0, 45, 90, 0.15)",
    pointerEvents: "auto",
  },
  navBtn: {
    background: "transparent",
    border: "none",
    padding: 10,
    cursor: "pointer",
    fontSize: 14,
    color: "#1E74D6",
  },
};
